### ISSUE TITLE
Gets last question wrong

### ISSUE THREAD

**Issue by TheSavageTeddy** [Roxiun/EPBot#8]
when the bot finishes the whole list, most of the time it gets the last question wrong.

**Comment by Roxiun** [comment]
Please provide more details and screenshot and/or a log (`EPBot/logs/main.log`)

**Comment by TheSavageTeddy** [comment]
it doesn't crash tho

**Comment by Roxiun** [comment]
Show a screenshot of it getting it wrong as well as send log file (log file logs everything even if its not a crash)

**Comment by Roxiun** [comment]
This issue has basically been fixed now. Slight EP bug caused this
